# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_customuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='customid',
            new_name='username',
        ),
    ]
