# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('carnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('broken1', models.CharField(blank=True, choices=[('범퍼', '범퍼'), ('도어', '도어'), ('유리', '유리'), ('A 필러', 'A 필러'), ('B 필러', 'B 필러'), ('C 필러', 'C 필러'), ('본넷', '본넷'), ('루프 판넬', '루프 판넬'), ('트렁크', '트렁크'), ('휠하우스', '휠하우스')], max_length=10, null=True)),
                ('broken2', models.CharField(blank=True, choices=[('범퍼', '범퍼'), ('도어', '도어'), ('유리', '유리'), ('A 필러', 'A 필러'), ('B 필러', 'B 필러'), ('C 필러', 'C 필러'), ('본넷', '본넷'), ('루프 판넬', '루프 판넬'), ('트렁크', '트렁크'), ('휠하우스', '휠하우스')], max_length=10, null=True)),
                ('broken3', models.CharField(blank=True, choices=[('범퍼', '범퍼'), ('도어', '도어'), ('유리', '유리'), ('A 필러', 'A 필러'), ('B 필러', 'B 필러'), ('C 필러', 'C 필러'), ('본넷', '본넷'), ('루프 판넬', '루프 판넬'), ('트렁크', '트렁크'), ('휠하우스', '휠하우스')], max_length=10, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail', models.CharField(blank=True, max_length=200, null=True)),
                ('extra', models.CharField(blank=True, choices=[('보험수리', '보험수리'), ('렌터카', '렌터카'), ('픽업 서비스', '픽업 서비스'), ('차대번호', '차대번호')], max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=11, null=True)),
                ('completed', models.NullBooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
