# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_request_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='broken1',
            field=models.CharField(blank=True, choices=[('범퍼', '범퍼'), ('도어', '도어'), ('유리', '유리'), ('A 필러', 'A 필러'), ('B 필러', 'B 필러'), ('C 필러', 'C 필러'), ('본넷', '본넷'), ('루프 판넬', '루프 판넬'), ('트렁크', '트렁크'), ('휠하우스', '휠하우스')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='broken2',
            field=models.CharField(blank=True, choices=[('범퍼', '범퍼'), ('도어', '도어'), ('유리', '유리'), ('A 필러', 'A 필러'), ('B 필러', 'B 필러'), ('C 필러', 'C 필러'), ('본넷', '본넷'), ('루프 판넬', '루프 판넬'), ('트렁크', '트렁크'), ('휠하우스', '휠하우스')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='broken3',
            field=models.CharField(blank=True, choices=[('범퍼', '범퍼'), ('도어', '도어'), ('유리', '유리'), ('A 필러', 'A 필러'), ('B 필러', 'B 필러'), ('C 필러', 'C 필러'), ('본넷', '본넷'), ('루프 판넬', '루프 판넬'), ('트렁크', '트렁크'), ('휠하우스', '휠하우스')], max_length=10, null=True),
        ),
    ]
