# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
