# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_request_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
