# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
                ('video', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('zone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
