# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='bnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
