# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noninsurancecost', models.CharField(blank=True, max_length=20, null=True)),
                ('insurancecost', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.CharField(blank=True, max_length=200, null=True)),
                ('completed', models.NullBooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate', to=settings.AUTH_USER_MODEL)),
                ('targetrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Request.Request')),
            ],
        ),
    ]
