# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estimate', '0003_auto_20170404_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='providedby',
            new_name='owner',
        ),
    ]
